### ISSUE TITLE
Camera zoom affects performance

### ISSUE THREAD

**Issue by rik-cross** [rik-cross/pygamepal#15]
Zooming in slows down the game, most likely due to drawing larger images. To see an example, run `fullExample.py` and walk towards the trees.

**Comment by rik-cross** [comment]
The main issue here is that the standard-sized source surface when zoomed in becomes quite large.

I've added a `worldSize` parameter to a scene, which can be set smaller if required.

A good fix for the future would be to get the viewable subsurface of the source surface, although that might not solve the problem (images would still be drawn to the surface ahead of getting the subsurface).

**Comment by mauricego** [comment]
Hi, did you find any solution? I have basically the same problem for my game...

**Comment by rik-cross** [comment]
In my case, the slowness was due to drawing to a surface the size of the screen, which was zoomed in quite a lot. The only solution I have is to use a smaller surface. I also know that you can use `.convert_alpha()` on textures to speed up the drawing.

**Comment by rik-cross** [comment]
Closing this, as it works well with reasonably-sized target surfaces.
